// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLa3d8-ovfzaWWAvZ5ftGBrAGXFkiv1bU',
    appId: '1:618061069876:web:bfb76e6dc76b97d7099461',
    messagingSenderId: '618061069876',
    projectId: 'pantry-pal-1e0e2',
    authDomain: 'pantry-pal-1e0e2.firebaseapp.com',
    storageBucket: 'pantry-pal-1e0e2.appspot.com',
    measurementId: 'G-SNQXD60YW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiVKvrMubVvqTw4acbW500-vTXxPtd3EU',
    appId: '1:618061069876:android:6ce82458f00844fd099461',
    messagingSenderId: '618061069876',
    projectId: 'pantry-pal-1e0e2',
    storageBucket: 'pantry-pal-1e0e2.appspot.com',
  );
}
